name: 栗染的博客
author: kuang
#baseurl: /
keywords: java,github,git,jekyll,gollum,jquery,flash,
description: 这是一首简单的小情歌
github: https://github.com/kuangqiu
email: kuangzhihong14p@163.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
